apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  namespace: k8s-ronymesquita-site
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: "letsencrypt-prod-issuer"
spec:
  tls:
    - hosts:
      - blog.ronymesquita.site
      - www.blog.ronymesquita.site
      secretName: tls-secret
  rules:
    - host: blog.ronymesquita.site
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: http
    # Alias to blog.ronymesquita.site
    - host: www.blog.ronymesquita.site
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: http
